@startuml
|AGI|
start

:Modell erstellen;

:Modell in DB anlegen;

|Fachamt|
:Darstellung (QML)
erstellen;

|AGI|
:Technische Metain-
formationen erfassen;

note left
- Datenquelle
- Darstellung DataSet
- Gruppierungen
- Identifier der DataProducts
end note

|Fachamt|
:Technische
Metainformationen
gegenpruefen;

:Dokumentieren;

note right
- Titel
- Beschreibung
- Stichworte / Synonyme
- Infos zu Erhebung / Nachfuerung
- Attributbeschreigung
end note

|AGI|
:Dokumentation
gegenpruefen;

:Publikationen
freigeben;

note left
Freigabe unfasst:
- Web GIS Client
- Datenabgabe (via Dienste und Dateien)
- Berechtigungen fuer DB-Direktzugriff
end note

end
@enduml