@startuml
|Kunde|
start
:Ebenen zusammenstellen
und Auschnitt definieren
(Im Web GIS Client);
:Downloadübersicht
anzeigen (Mini-Webapp);
if (Spezialbestellung?) then (nein)
	:Selbstbedienung;
else (ja)
	:Web-Formular 
    ausfüllen;
    |AGI|
    :Bestellung abwickeln;
    :Webtransfer an Kunde;
endif
|Kunde|
end
@enduml