@startuml
|AGI|
start

:Modell erstellen;

note left
Gemeinsam mit Fachamt:
- Objektkatalog erarbeiten
- INTERLIS-Modell entwerfen
- Nach Review: Modell publizieren
end note

:Modell in DB anlegen;

:Technische Metain-
formationen erfassen;

note left
- Datenquelle
- Darstellung DataSet
- Gruppierungen
- Identifier der DataProducts
- Zugriffssteürung
- ...
end note

|GIS-Koordinator|
:Darstellung (QML)
erstellen;

:Dokumentieren;

note right
- Titel
- Beschreibung
- Stichworte / Synonyme
- Kontaktinformationen
- Infos zu Erhebung / Nachfürung
- Attributbeschreibung
- ...
end note

:Gesamtkonfiguration
prüfen;

note right
Umfasst:
- Drücken des Magicbutton
- Prüfen der Konfig via WGC, SO-Locator, ...
end note

|AGI|
:Dokumentation
gegenprüfen;

:Publikationen
freigeben;

note left
Freigabe umfasst:
- Web GIS Client
- Datenabgabe (via Dienste und Dateien)
- Berechtigungen für DB-Direktzugriff
end note

end
@enduml