@startuml
|AGI|
start

:Modell erstellen;

:Modell in DB anlegen;

:Technische Metain-
formationen erfassen;

note left
- Datenquelle
- Darstellung DataSet
- Gruppierungen
- Identifier der DataProducts
- Zugriffssteuerung
- ...
end note

|Fachamt|
:Darstellung (QML)
erstellen;

:Dokumentieren;

note right
- Titel
- Beschreibung
- Stichworte / Synonyme
- Kontaktinformationen
- Infos zu Erhebung / Nachfuerung
- Attributbeschreibung
- ...
end note

:Gesamtkonfiguration
pruefen;

note right
Umfasst:
- Druecken des Magicbutton
- Pruefen der Konfig via WGC, SO-Locator, ...
end note

|AGI|
:Dokumentation
gegenpruefen;

:Publikationen
freigeben;

note left
Freigabe umfasst:
- Web GIS Client
- Datenabgabe (via Dienste und Dateien)
- Berechtigungen fuer DB-Direktzugriff
end note

end
@enduml