@startuml

abstract class "DataProduct (DP)" as dp {
    identifier* : string
    inWGC* : bool
    title: string
    remarks: string
}

abstract class "ProductSet (PS)" as ps

class "LayerGroup (LG)" as lg

class "Map (MAP)" as map {
  foreground* : bool
}

class "TableOfContents (TOC)" as toc {
    name* : string
    remarks : string
}

abstract class "SingleActor (SA)" as sa

class "FacadeLayer (FL)" as fl

class "PostgresDS (PDS)" as pds {
    tablename* : string
    inDataServices* : bool
    def_transparency* : int
    qml_content* : string
}

class "DatasetListProperties (DLP)" as dlp << (H, grey) Association Class >> {
    visibility*: bool
    sort*: int
    transparency: int
}

class "SingleActorListProperties (SLP)" as slp << (H, grey) Association Class >> {
    visibility*: bool
    sort*: int
    transparency: int
}

dp <|-- ps
ps <|-- lg
ps <|-- map
  
dp <|-- sa

sa <|-- pds
sa <|-- fl

ps "0..*" - "1..*" toc : [ordered]

toc "0..*" - "1..*" sa : [Class: SLP]
fl "0..*" - "1..*" pds : [Class: DLP]

' layout help
sa -[hidden]> slp
pds -[hidden]> dlp

@enduml
