@startuml

abstract class "DataProduct (DP)" as dp {
    inWGC* : bool
    title: string
    remarks: string
}

class "ProductSet (PS)" as ps {
    identifier* : string
}

abstract class "SingleActor (SA)" as sa {
    identifier* : string
}

class "FacadeLayer (FL)" as fl

class "PostgresDS (PDS)" as pds {
    tablename* : string
    inDataServices* : bool
    def_transparency* : int
}

class "PropertiesInList (PIL)" as pil << (H, grey) Association Class >> {
    visibility*: bool
    rank*: int
    transparency: int
}

dp <|-- ps

dp <|-- sa
sa <|-- pds
sa <|-- fl

ps "1..*" - "1..*" sa : [Class: PIL]
fl "0..*" - "1..*" pds : [Class: PIL]

' layout help
sa -[hidden]> pil

@enduml
