@startuml
package Flow {

  class "SingleLayer (SL)" as sl << package Core >> {
  }

  class "Artefact (AF)" as af {
  	name*  : string
    description : string
  }

  class "ArtefactType (AT)" as at {
  	type* : string
    description : string
  }

  class "LayerUsage" as lu {
  	usagetype* : enum
  }

  sl "1" -- "*" lu
  lu "1..*" -- "1" af
  af "*" -right- "1" at
}
@enduml