@startuml

package Map {
  abstract class "DataProduct (DP)" as dp {
      identifier* : string
      title: string
      synonyms: string
      description: string
      keywords: string
      remarks: string
      inWms* : bool
      inWGC* : bool
  }
  
  abstract class "ProductSet (PS)" as ps
  class "LayerGroup (LG)" as lg

  class "Map (MAP)" as map {
    foreground* : bool
  }
  
  class "DataSetList (DSL)" as dsl {
    name* : string
    remarks : string
  }
  
  abstract class "SingleActor (SA)" as sa

  class "FacadeLayer (FL)" as fl

  class "SingleLayer (SL)" as sl {
    owner* : reference
    dataPublished* : bool
  }
  
  class "PropertiesInList (PIL)" as pil << (H, grey) Association Class >> {
  	visibility*: bool
    rank*: int
    transparency: int
  }
  
  dp <|-- ps
  ps <|-- lg
  ps <|-- map
  
  dp <|-- sa
  sa <|-- sl
  sa <|-- fl
  
  ps "0..*" - "1..*" dsl : [ordered]
  
  dsl "0..*" - "1..*" sa : [Class: PIL]  
  fl "0..*" - "1..*" sl : [Class: PIL]
  
  ' layout help
  sa -[hidden]> pil
}

@enduml