@startuml

package Map {
  abstract class "DataProduct (DP)" as dp {
      identifier* : string
      title: string
      synonyms: string
      description: string
      keywords: string
      remarks: string
      inWms* : bool
      inWGC* : bool
  }
  
  abstract class "ProductSet (PS)" as ps
  class "LayerGroup (LG)" as lg

  class "Map (MAP)" as map {
    foreground* : bool
  }
  
  class "TableOfContents (TOC)" as toc {
    name* : string
    remarks : string
  }
  
  abstract class "SingleActor (SA)" as sa

  class "FacadeLayer (FL)" as fl

  class "SingleLayer (SL)" as sl {
    owner* : reference
    dataPublished* : bool
  }
  
  class "SingleLayerLinkProperties (SLL)" as sll << (H, grey) Association Class >> {
      visibility*: bool
      sort*: int
      transparency: int
  }

  class "SingleActorLinkProperties (SAL)" as sal << (H, grey) Association Class >> {
      visibility*: bool
      sort*: int
      transparency: int
  }
  
  dp <|-- ps
  ps <|-- lg
  ps <|-- map
  
  dp <|-- sa
  sa <|-- sl
  sa <|-- fl
  
  ps "0..*" - "1..*" toc : [ordered]
  
  toc "0..*" - "1..*" sa : [Class: SAL]  
  fl "0..*" - "1..*" sl : [Class: SLL]
  
  'layout help
  sa -[hidden]> sal
  sl -[hidden]> sll
}

@enduml