@startuml
left to right direction

:Planungs- /\nGeo-Büro: as büro
:Datenintegrator: as int
:SO-Datenspezialist: as data
:GIS-Koord.\n/ AGI: as exporter

(Datenbezug\nzusammenstellen) as bundle
(Daten downloaden) as load
(Als XTF downloaden) as xtf
(Manüll exportieren) as manüll

load <|-- xtf

büro --> bundle
büro --> load
int --> load
data --> xtf

exporter --> manüll
@enduml